name: Deploy to Dev Server

on:
  workflow_run:
    workflows: ["build-and-push"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # This condition ensures the job only runs if the triggering workflow was successful
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        uses: IgorNadj/github-actions/deploy@main
        with:
          ssh-private-key: ${{ secrets.DEV_SERVER_SSH_KEY }}
